### PR TITLE
add easystar-js plugin

### PR DESCRIPTION
**Pull request by SparedRay**
this is my first pull request, so let me know if there's something that could be better

### CODE REVIEW

**Comment by elisee** [comment]
Hey sorry for not answering earlier. Will take a look at your plugin before the end of the month!

**Comment by elisee** [comment]
@SparedRay looking good. Why is `martinor` the author though, is it another name of yours? Might make more sense to use `SparedRay` to make it easy to connect with you on GitHub?

**Comment by SparedRay** [comment]
@elisee Yes, i normally use `martinor` as my name (in fact i dont even know why i named this account as `SparedRay`) but i can change it, its just a name at the end.

**Comment by elisee** [comment]
Thanks for the change.

I merged it but it does not install correctly currently. The root folder inside the ZIP must match the ZIP's filename. Can you reupload a ZIP with the correct folder name inside? Thanks!

**Comment by SparedRay** [comment]
Done, i already change the name of the root folder on the zip

**Comment by elisee** [comment]
Cool, installation works now!

**Pull request merged**
